name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # fetch all history so that last modified date-times are accurate

      - name: 🐍 Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: 🧳 Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      # - name: 👷‍ Install Dot and pandoc
      #   run: |
      #     conda install -c conda-forge pandoc
      #     conda install -c conda-forge ipython
      #     pip install sphinxcontrib-websupport
      #     sudo apt update
      #     sudo apt install -y graphviz

      - name: 👷‍ Install dependencies
        shell: bash
        run: |
          pip install --upgrade pip
          pip install -r docs/requirements.txt

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup IJava
        env:
          ijava-version: 1.3.0
        run: |
          wget https://github.com/SpencerPark/IJava/releases/download/v${{ env.ijava-version }}/ijava-${{ env.ijava-version }}.zip
          unzip ijava-1.3.0.zip -d IJava
          cd IJava
          python3 install.py --sys-prefix

      - name: 🔧 Build HTML
        run: |
          cd docs
          make html

      # remove the folder when building for deployment as it takes two thirds of disk space
      - name: 🔥 Clean up files
        run: |
          rm -r docs/_build/doctrees/ IJava/

      - name: 🚀 Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html

